baseURL = 'https://bio-recap.github.io/Liu_2016/'
languageCode = 'en-us'
title = 'Liu_2016'
theme = 'hugo-theme-relearn'

[menu]
[[menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHub"
    url = 'https://github.com/bio-recap/Liu_2016'
    weight = 10

[[menu.shortcuts]]
    name = "<i class='fas fa-file'></i> All Analysis Files"
    url = 'https://github.com/bio-recap/Liu_2016/tree/main/analysis/'
    weight = 15

[[menu.shortcuts]]
    name = "<i class='fas fa-dna'></i> Back to Bio-Recap Directory" 
    url = 'https://bio-recap.github.io/directory/projects_directory/all_categories/index.html'
    weight = 20

[[menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bullhorn'></i> Acknowledgements"
    url = 'entry_and_reqs/credits/'
    weight = 30

[params]
  additionalContentLanguage = ['en']
  alwaysopen = ''
  breadcrumbSeparator = '>'
  collapsibleMenu = true
  customMathJaxURL = ''
  customMermaidURL = ''
  customOpenapiURL = ''
  description = ''
  disableAssetsBusting = false
  disableBreadcrumb = false
  disableExplicitIndexURLs = false
  disableGeneratorVersion = false
  disableHoverBlockCopyToClipBoard = false
  disableInlineCopyToClipBoard = true
  disableLandingPageButton = true
  disableLanguageSwitchingButton = false
  disableMathJax = true
  disableMermaid = true
  disableNextPrev = false
  disableOpenapi = true
  disableRandomIds = false
  disableRootBreadcrumb = true
  disableSearch = false
  disableSearchHiddenPages = false
  disableSeoHiddenPages = true
  disableShortcutsTitle = false
  disableTagHiddenPages = false
  disableTermBreadcrumbs = false
  disableToc = false
  externalLinkTarget = '_blank'
  highlightWrap = true
  images = ['images/hero.png']
  mathJaxInitialize = '{}'
  mermaidInitialize = '{ "securityLevel": "loose" }'
  mermaidZoom = true
  ordersectionsby = 'weight'
  showVisitedLinks = true
  themeVariantModifier = ''
  titleSeparator = '::'

  [params.author]
    name = 'Colton Robbins'

  [params.image]
    errorlevel = 'warning'

  [params.imageEffects]
    border = true
    lightbox = true
    shadow = true

  [params.link]
    errorlevel = 'warning'

  [params.social]
    facebook_admin = ''
    twitter = ''

[[params.themeVariant]]
    auto = []
    identifier = 'relearn-auto'
    name = 'Relearn Light/Dark'

[[params.themeVariant]]
    identifier = 'relearn-light'

[[params.themeVariant]]
    identifier = 'relearn-dark'

[[params.themeVariant]]
    identifier = 'relearn-bright'

[[params.themeVariant]]
    auto = ['zen-light', 'zen-dark']
    identifier = 'zen-auto'
    name = 'Zen Light/Dark'

[[params.themeVariant]]
    identifier = 'zen-light'

[[params.themeVariant]]
    identifier = 'zen-dark'

[[params.themeVariant]]
    identifier = 'neon'

[[params.themeVariant]]
    identifier = 'learn'

[[params.themeVariant]]
    identifier = 'blue'

[[params.themeVariant]]
    identifier = 'green'

[[params.themeVariant]]
    identifier = 'red'